"""Hygiene smell — GOD CLASS (Fowler): one class owns persistence, HTTP, email,
billing, reporting, and auth. Low cohesion, many responsibilities. Mirror splits it."""


class Application:
    def connect_db(self): ...
    def query(self, sql): ...
    def migrate(self): ...
    def handle_request(self, req): ...
    def route(self, path): ...
    def render_template(self, t): ...
    def send_email(self, to, body): ...
    def charge_card(self, amount): ...
    def refund(self, txn): ...
    def generate_invoice(self, order): ...
    def build_report(self, kind): ...
    def export_csv(self, rows): ...
    def login(self, user, pw): ...
    def hash_password(self, pw): ...
    def issue_token(self, user): ...
    def check_permission(self, user, action): ...
