"""SAFE mirror — responsibilities split into cohesive single-purpose classes."""


class Database:
    def connect(self): ...
    def query(self, sql): ...


class Mailer:
    def send(self, to, body): ...


class Billing:
    def charge(self, amount): ...
    def refund(self, txn): ...


class Auth:
    def login(self, user, pw): ...
    def issue_token(self, user): ...
